.TH "_crtc" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_crtc
.SH SYNOPSIS
.br
.PP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "\fBname_t\fP \fBcrtc\fP"
.br
.ti -1c
.RI "Bool \fBchanging\fP"
.br
.ti -1c
.RI "XRRCrtcInfo * \fBcrtc_info\fP"
.br
.ti -1c
.RI "XRRModeInfo * \fBmode_info\fP"
.br
.ti -1c
.RI "XRRPanning * \fBpanning_info\fP"
.br
.ti -1c
.RI "\fBint\fP \fBx\fP"
.br
.ti -1c
.RI "\fBint\fP \fBy\fP"
.br
.ti -1c
.RI "Rotation \fBrotation\fP"
.br
.ti -1c
.RI "\fBoutput_t\fP ** \fBoutputs\fP"
.br
.ti -1c
.RI "\fBint\fP \fBnoutput\fP"
.br
.ti -1c
.RI "\fBtransform_t\fP \fBcurrent_transform\fP"
.br
.ti -1c
.RI "\fBtransform_t\fP \fBpending_transform\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 xrandr\&.c 檔案之第 201 行\&.
.SH "資料成員說明文件"
.PP 
.SS "Bool _crtc::changing"

.PP
定義在 xrandr\&.c 檔案之第 203 行\&.
.SS "\fBname_t\fP _crtc::crtc"

.PP
定義在 xrandr\&.c 檔案之第 202 行\&.
.SS "XRRCrtcInfo* _crtc::crtc_info"

.PP
定義在 xrandr\&.c 檔案之第 204 行\&.
.SS "\fBtransform_t\fP _crtc::current_transform"

.PP
定義在 xrandr\&.c 檔案之第 213 行\&.
.SS "XRRModeInfo* _crtc::mode_info"

.PP
定義在 xrandr\&.c 檔案之第 206 行\&.
.SS "\fBint\fP _crtc::noutput"

.PP
定義在 xrandr\&.c 檔案之第 212 行\&.
.SS "\fBoutput_t\fP** _crtc::outputs"

.PP
定義在 xrandr\&.c 檔案之第 211 行\&.
.SS "XRRPanning* _crtc::panning_info"

.PP
定義在 xrandr\&.c 檔案之第 207 行\&.
.SS "\fBtransform_t\fP _crtc::pending_transform"

.PP
定義在 xrandr\&.c 檔案之第 213 行\&.
.SS "Rotation _crtc::rotation"

.PP
定義在 xrandr\&.c 檔案之第 210 行\&.
.SS "\fBint\fP _crtc::x"

.PP
定義在 xrandr\&.c 檔案之第 208 行\&.
.SS "\fBint\fP _crtc::y"

.PP
定義在 xrandr\&.c 檔案之第 209 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
