.TH "/home/odin/Desktop/program/usbdisp_linux/libusbdisp 目錄參考文件" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/odin/Desktop/program/usbdisp_linux/libusbdisp 目錄參考文件
.SH SYNOPSIS
.br
.PP
.SS "目錄"

.in +1c
.ti -1c
.RI "目錄 \fBdeb_install\fP"
.br
.ti -1c
.RI "目錄 \fBlibenc\fP"
.br
.in -1c
.SS "檔案"

.in +1c
.ti -1c
.RI "檔案 \fBcapture\&.cpp\fP"
.br
.ti -1c
.RI "檔案 \fBcapture\&.h\fP"
.br
.ti -1c
.RI "檔案 \fBmain\&.c\fP"
.br
.ti -1c
.RI "檔案 \fBusbdev\&.cpp\fP"
.br
.ti -1c
.RI "檔案 \fBusbdev\&.h\fP"
.br
.ti -1c
.RI "檔案 \fBusbDisplay\&.cpp\fP"
.br
.ti -1c
.RI "檔案 \fBusbDisplay\&.h\fP"
.br
.ti -1c
.RI "檔案 \fBxrandr\&.c\fP"
.br
.ti -1c
.RI "檔案 \fBxrandr\&.h\fP"
.br
.in -1c
