.TH "/home/odin/Desktop/program/usbdisp_linux/libusbdisp/deb_install/com.racertech.usbdisp-1.0.0/opt/apps/com.racertech.usbdisp/files/evdi/module 目錄參考文件" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/odin/Desktop/program/usbdisp_linux/libusbdisp/deb_install/com.racertech.usbdisp-1.0.0/opt/apps/com.racertech.usbdisp/files/evdi/module 目錄參考文件
.SH SYNOPSIS
.br
.PP
.SS "檔案"

.in +1c
.ti -1c
.RI "檔案 \fBevdi_connector\&.c\fP"
.br
.ti -1c
.RI "檔案 \fBevdi_cursor\&.c\fP"
.br
.ti -1c
.RI "檔案 \fBevdi_cursor\&.h\fP"
.br
.ti -1c
.RI "檔案 \fBevdi_debug\&.c\fP"
.br
.ti -1c
.RI "檔案 \fBevdi_debug\&.h\fP"
.br
.ti -1c
.RI "檔案 \fBevdi_drm\&.h\fP"
.br
.ti -1c
.RI "檔案 \fBevdi_drm_drv\&.c\fP"
.br
.ti -1c
.RI "檔案 \fBevdi_drm_drv\&.h\fP"
.br
.ti -1c
.RI "檔案 \fBevdi_encoder\&.c\fP"
.br
.ti -1c
.RI "檔案 \fBevdi_fb\&.c\fP"
.br
.ti -1c
.RI "檔案 \fBevdi_gem\&.c\fP"
.br
.ti -1c
.RI "檔案 \fBevdi_i2c\&.c\fP"
.br
.ti -1c
.RI "檔案 \fBevdi_i2c\&.h\fP"
.br
.ti -1c
.RI "檔案 \fBevdi_ioc32\&.c\fP"
.br
.ti -1c
.RI "檔案 \fBevdi_modeset\&.c\fP"
.br
.ti -1c
.RI "檔案 \fBevdi_painter\&.c\fP"
.br
.ti -1c
.RI "檔案 \fBevdi_params\&.c\fP"
.br
.ti -1c
.RI "檔案 \fBevdi_params\&.h\fP"
.br
.ti -1c
.RI "檔案 \fBevdi_platform_dev\&.c\fP"
.br
.ti -1c
.RI "檔案 \fBevdi_platform_dev\&.h\fP"
.br
.ti -1c
.RI "檔案 \fBevdi_platform_drv\&.c\fP"
.br
.ti -1c
.RI "檔案 \fBevdi_platform_drv\&.h\fP"
.br
.ti -1c
.RI "檔案 \fBevdi_sysfs\&.c\fP"
.br
.ti -1c
.RI "檔案 \fBevdi_sysfs\&.h\fP"
.br
.in -1c
