.TH "_output_prop" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_output_prop
.SH SYNOPSIS
.br
.PP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "struct \fB_output_prop\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBchar\fP * \fBname\fP"
.br
.ti -1c
.RI "\fBchar\fP * \fBvalue\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 xrandr\&.c 檔案之第 216 行\&.
.SH "資料成員說明文件"
.PP 
.SS "\fBchar\fP* _output_prop::name"

.PP
定義在 xrandr\&.c 檔案之第 218 行\&.
.SS "struct \fB_output_prop\fP* _output_prop::next"

.PP
定義在 xrandr\&.c 檔案之第 217 行\&.
.SS "\fBchar\fP* _output_prop::value"

.PP
定義在 xrandr\&.c 檔案之第 219 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
