.TH "_transform" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_transform
.SH SYNOPSIS
.br
.PP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "XTransform \fBtransform\fP"
.br
.ti -1c
.RI "const \fBchar\fP * \fBfilter\fP"
.br
.ti -1c
.RI "\fBint\fP \fBnparams\fP"
.br
.ti -1c
.RI "XFixed * \fBparams\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 xrandr\&.c 檔案之第 194 行\&.
.SH "資料成員說明文件"
.PP 
.SS "const \fBchar\fP* _transform::filter"

.PP
定義在 xrandr\&.c 檔案之第 196 行\&.
.SS "\fBint\fP _transform::nparams"

.PP
定義在 xrandr\&.c 檔案之第 197 行\&.
.SS "XFixed* _transform::params"

.PP
定義在 xrandr\&.c 檔案之第 198 行\&.
.SS "XTransform _transform::transform"

.PP
定義在 xrandr\&.c 檔案之第 195 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
