.TH "_umode" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_umode
.SH SYNOPSIS
.br
.PP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "struct \fB_umode\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBumode_action_t\fP \fBaction\fP"
.br
.ti -1c
.RI "XRRModeInfo \fBmode\fP"
.br
.ti -1c
.RI "\fBname_t\fP \fBoutput\fP"
.br
.ti -1c
.RI "\fBname_t\fP \fBname\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 xrandr\&.c 檔案之第 272 行\&.
.SH "資料成員說明文件"
.PP 
.SS "\fBumode_action_t\fP _umode::action"

.PP
定義在 xrandr\&.c 檔案之第 275 行\&.
.SS "XRRModeInfo _umode::mode"

.PP
定義在 xrandr\&.c 檔案之第 276 行\&.
.SS "\fBname_t\fP _umode::name"

.PP
定義在 xrandr\&.c 檔案之第 278 行\&.
.SS "struct \fB_umode\fP* _umode::next"

.PP
定義在 xrandr\&.c 檔案之第 273 行\&.
.SS "\fBname_t\fP _umode::output"

.PP
定義在 xrandr\&.c 檔案之第 277 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
