.TH "AndroidEngine" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AndroidEngine
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <capture\&.h>\fP
.PP
繼承自 \fBEncodeEngine\fP\&.
.SS "公開方法(Public Methods)"

.in +1c
.ti -1c
.RI "\fBAndroidEngine\fP ()"
.br
.ti -1c
.RI "virtual \fB~AndroidEngine\fP ()"
.br
.ti -1c
.RI "bool \fBCreateDevice\fP (\fBint\fP fd)"
.br
.ti -1c
.RI "bool \fBCreateDevice\fP (libusb_device *dev)"
.br
.ti -1c
.RI "bool \fBSetDevResolution\fP (\fBint\fP width, \fBint\fP height)"
.br
.in -1c
.SS "額外的繼承成員"
.SH "詳細描述"
.PP 
定義在 capture\&.h 檔案之第 12 行\&.
.SH "建構子與解構子說明文件"
.PP 
.SS "AndroidEngine::AndroidEngine ()\fC [inline]\fP"

.PP
定義在 capture\&.h 檔案之第 15 行\&.
.SS "virtual AndroidEngine::~AndroidEngine ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
定義在 capture\&.h 檔案之第 20 行\&.
.SH "函式成員說明文件"
.PP 
.SS "bool AndroidEngine::CreateDevice (\fBint\fP fd)\fC [inline]\fP"

.PP
定義在 capture\&.h 檔案之第 25 行\&.
.SS "bool AndroidEngine::CreateDevice (libusb_device * dev)\fC [inline]\fP"

.PP
定義在 capture\&.h 檔案之第 31 行\&.
.SS "bool AndroidEngine::SetDevResolution (\fBint\fP width, \fBint\fP height)\fC [inline]\fP"

.PP
定義在 capture\&.h 檔案之第 38 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
