.TH "APP0infotype" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
APP0infotype
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jpeg_enc\&.h>\fP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "\fBWORD\fP \fBmarker\fP"
.br
.ti -1c
.RI "\fBWORD\fP \fBlength\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBJFIFsignature\fP [5]"
.br
.ti -1c
.RI "\fBBYTE\fP \fBversionhi\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBversionlo\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBxyunits\fP"
.br
.ti -1c
.RI "\fBWORD\fP \fBxdensity\fP"
.br
.ti -1c
.RI "\fBWORD\fP \fBydensity\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBthumbnwidth\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBthumbnheight\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 jpeg_enc\&.h 檔案之第 47 行\&.
.SH "資料成員說明文件"
.PP 
.SS "\fBBYTE\fP APP0infotype::JFIFsignature[5]"

.PP
定義在 jpeg_enc\&.h 檔案之第 50 行\&.
.SS "\fBWORD\fP APP0infotype::length"

.PP
定義在 jpeg_enc\&.h 檔案之第 49 行\&.
.SS "\fBWORD\fP APP0infotype::marker"

.PP
定義在 jpeg_enc\&.h 檔案之第 48 行\&.
.SS "\fBBYTE\fP APP0infotype::thumbnheight"

.PP
定義在 jpeg_enc\&.h 檔案之第 57 行\&.
.SS "\fBBYTE\fP APP0infotype::thumbnwidth"

.PP
定義在 jpeg_enc\&.h 檔案之第 56 行\&.
.SS "\fBBYTE\fP APP0infotype::versionhi"

.PP
定義在 jpeg_enc\&.h 檔案之第 51 行\&.
.SS "\fBBYTE\fP APP0infotype::versionlo"

.PP
定義在 jpeg_enc\&.h 檔案之第 52 行\&.
.SS "\fBWORD\fP APP0infotype::xdensity"

.PP
定義在 jpeg_enc\&.h 檔案之第 54 行\&.
.SS "\fBBYTE\fP APP0infotype::xyunits"

.PP
定義在 jpeg_enc\&.h 檔案之第 53 行\&.
.SS "\fBWORD\fP APP0infotype::ydensity"

.PP
定義在 jpeg_enc\&.h 檔案之第 55 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
