.TH "blockheader_t" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
blockheader_t
.SH SYNOPSIS
.br
.PP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "unsigned \fBint\fP \fBquality\fP: 2"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBlen\fP: 8"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBblock_index\fP:16"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBreserved0\fP: 1"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBend\fP: 1"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBid\fP: 4"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 Encoder\&.cpp 檔案之第 6 行\&.
.SH "資料成員說明文件"
.PP 
.SS "unsigned \fBint\fP blockheader_t::block_index"

.PP
定義在 Encoder\&.cpp 檔案之第 9 行\&.
.SS "unsigned \fBint\fP blockheader_t::end"

.PP
定義在 Encoder\&.cpp 檔案之第 11 行\&.
.SS "unsigned \fBint\fP blockheader_t::id"

.PP
定義在 Encoder\&.cpp 檔案之第 12 行\&.
.SS "unsigned \fBint\fP blockheader_t::len"

.PP
定義在 Encoder\&.cpp 檔案之第 8 行\&.
.SS "unsigned \fBint\fP blockheader_t::quality"

.PP
定義在 Encoder\&.cpp 檔案之第 7 行\&.
.SS "unsigned \fBint\fP blockheader_t::reserved0"

.PP
定義在 Encoder\&.cpp 檔案之第 10 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
