.TH "box_t" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
box_t
.SH SYNOPSIS
.br
.PP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "\fBint\fP \fBx1\fP"
.br
.ti -1c
.RI "\fBint\fP \fBy1\fP"
.br
.ti -1c
.RI "\fBint\fP \fBx2\fP"
.br
.ti -1c
.RI "\fBint\fP \fBy2\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 xrandr\&.c 檔案之第 144 行\&.
.SH "資料成員說明文件"
.PP 
.SS "\fBint\fP box_t::x1"

.PP
定義在 xrandr\&.c 檔案之第 145 行\&.
.SS "\fBint\fP box_t::x2"

.PP
定義在 xrandr\&.c 檔案之第 145 行\&.
.SS "\fBint\fP box_t::y1"

.PP
定義在 xrandr\&.c 檔案之第 145 行\&.
.SS "\fBint\fP box_t::y2"

.PP
定義在 xrandr\&.c 檔案之第 145 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
