.TH "/home/odin/Desktop/program/usbdisp_linux/libusbdisp/capture.h" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/odin/Desktop/program/usbdisp_linux/libusbdisp/capture.h
.SH SYNOPSIS
.br
.PP
\fC#include 'ThreadBase\&.h'\fP
.br
\fC#include 'event\&.h'\fP
.br
\fC#include 'usbdev\&.h'\fP
.br
\fC#include 'EncodeEngine\&.h'\fP
.br

.SS "複合項目"

.in +1c
.ti -1c
.RI "class \fBAndroidEngine\fP"
.br
.ti -1c
.RI "class \fBCapture\fP"
.br
.in -1c
.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
