.TH "/home/odin/Desktop/program/usbdisp_linux/libusbdisp/libenc/debug_trace.c" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/odin/Desktop/program/usbdisp_linux/libusbdisp/libenc/debug_trace.c
.SH SYNOPSIS
.br
.PP
\fC#include 'debug_trace\&.h'\fP
.br

.SS "函式"

.in +1c
.ti -1c
.RI "void \fBDBGTRACE\fP (\fBint\fP mask, const \fBchar\fP *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBMSG\fP (const \fBchar\fP *fmt,\&.\&.\&.)"
.br
.in -1c
.SS "變數"

.in +1c
.ti -1c
.RI "unsigned \fBint\fP \fBdebug_mask\fP = \fBDBG_ALL\fP"
.br
.in -1c
.SH "函式說明文件"
.PP 
.SS "void DBGTRACE (\fBint\fP mask, const \fBchar\fP * fmt,  \&.\&.\&.)"

.PP
定義在 debug_trace\&.c 檔案之第 7 行\&.
.SS "void MSG (const \fBchar\fP * fmt,  \&.\&.\&.)"

.PP
定義在 debug_trace\&.c 檔案之第 25 行\&.
.SH "變數說明文件"
.PP 
.SS "unsigned \fBint\fP debug_mask = \fBDBG_ALL\fP"

.PP
定義在 debug_trace\&.c 檔案之第 5 行\&.
.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
