.TH "DQTinfotype" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DQTinfotype
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jpeg_enc\&.h>\fP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "\fBWORD\fP \fBmarker\fP"
.br
.ti -1c
.RI "\fBWORD\fP \fBlength\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBQTYinfo\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBYtable\fP [64]"
.br
.ti -1c
.RI "\fBBYTE\fP \fBQTCbinfo\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBCbtable\fP [64]"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 jpeg_enc\&.h 檔案之第 98 行\&.
.SH "資料成員說明文件"
.PP 
.SS "\fBBYTE\fP DQTinfotype::Cbtable[64]"

.PP
定義在 jpeg_enc\&.h 檔案之第 105 行\&.
.SS "\fBWORD\fP DQTinfotype::length"

.PP
定義在 jpeg_enc\&.h 檔案之第 100 行\&.
.SS "\fBWORD\fP DQTinfotype::marker"

.PP
定義在 jpeg_enc\&.h 檔案之第 99 行\&.
.SS "\fBBYTE\fP DQTinfotype::QTCbinfo"

.PP
定義在 jpeg_enc\&.h 檔案之第 104 行\&.
.SS "\fBBYTE\fP DQTinfotype::QTYinfo"

.PP
定義在 jpeg_enc\&.h 檔案之第 101 行\&.
.SS "\fBBYTE\fP DQTinfotype::Ytable[64]"

.PP
定義在 jpeg_enc\&.h 檔案之第 103 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
