.TH "drm_evdi_grabpix32" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drm_evdi_grabpix32
.SH SYNOPSIS
.br
.PP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "uint32_t \fBmode\fP"
.br
.ti -1c
.RI "int32_t \fBbuf_width\fP"
.br
.ti -1c
.RI "int32_t \fBbuf_height\fP"
.br
.ti -1c
.RI "int32_t \fBbuf_byte_stride\fP"
.br
.ti -1c
.RI "uint32_t \fBbuffer_ptr32\fP"
.br
.ti -1c
.RI "int32_t \fBnum_rects\fP"
.br
.ti -1c
.RI "uint32_t \fBrects_ptr32\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 evdi_ioc32\&.c 檔案之第 45 行\&.
.SH "資料成員說明文件"
.PP 
.SS "int32_t drm_evdi_grabpix32::buf_byte_stride"

.PP
定義在 evdi_ioc32\&.c 檔案之第 49 行\&.
.SS "int32_t drm_evdi_grabpix32::buf_height"

.PP
定義在 evdi_ioc32\&.c 檔案之第 48 行\&.
.SS "int32_t drm_evdi_grabpix32::buf_width"

.PP
定義在 evdi_ioc32\&.c 檔案之第 47 行\&.
.SS "uint32_t drm_evdi_grabpix32::buffer_ptr32"

.PP
定義在 evdi_ioc32\&.c 檔案之第 50 行\&.
.SS "uint32_t drm_evdi_grabpix32::mode"

.PP
定義在 evdi_ioc32\&.c 檔案之第 46 行\&.
.SS "int32_t drm_evdi_grabpix32::num_rects"

.PP
定義在 evdi_ioc32\&.c 檔案之第 51 行\&.
.SS "uint32_t drm_evdi_grabpix32::rects_ptr32"

.PP
定義在 evdi_ioc32\&.c 檔案之第 52 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
