.TH "drm_evdi_event_mode_changed" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drm_evdi_event_mode_changed
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <evdi_drm\&.h>\fP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "struct drm_event \fBbase\fP"
.br
.ti -1c
.RI "int32_t \fBhdisplay\fP"
.br
.ti -1c
.RI "int32_t \fBvdisplay\fP"
.br
.ti -1c
.RI "int32_t \fBvrefresh\fP"
.br
.ti -1c
.RI "int32_t \fBbits_per_pixel\fP"
.br
.ti -1c
.RI "uint32_t \fBpixel_format\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 evdi_drm\&.h 檔案之第 31 行\&.
.SH "資料成員說明文件"
.PP 
.SS "struct drm_event drm_evdi_event_mode_changed::base"

.PP
定義在 evdi_drm\&.h 檔案之第 28 行\&.
.SS "int32_t drm_evdi_event_mode_changed::bits_per_pixel"

.PP
定義在 evdi_drm\&.h 檔案之第 36 行\&.
.SS "int32_t drm_evdi_event_mode_changed::hdisplay"

.PP
定義在 evdi_drm\&.h 檔案之第 33 行\&.
.SS "uint32_t drm_evdi_event_mode_changed::pixel_format"

.PP
定義在 evdi_drm\&.h 檔案之第 37 行\&.
.SS "int32_t drm_evdi_event_mode_changed::vdisplay"

.PP
定義在 evdi_drm\&.h 檔案之第 34 行\&.
.SS "int32_t drm_evdi_event_mode_changed::vrefresh"

.PP
定義在 evdi_drm\&.h 檔案之第 35 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
