.TH "drm_evdi_event_ddcci_data" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drm_evdi_event_ddcci_data
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <evdi_drm\&.h>\fP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "struct drm_event \fBbase\fP"
.br
.ti -1c
.RI "unsigned \fBchar\fP \fBbuffer\fP [\fBDDCCI_BUFFER_SIZE\fP]"
.br
.ti -1c
.RI "uint32_t \fBbuffer_length\fP"
.br
.ti -1c
.RI "uint16_t \fBflags\fP"
.br
.ti -1c
.RI "uint16_t \fBaddress\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 evdi_drm\&.h 檔案之第 105 行\&.
.SH "資料成員說明文件"
.PP 
.SS "uint16_t drm_evdi_event_ddcci_data::address"

.PP
定義在 evdi_drm\&.h 檔案之第 110 行\&.
.SS "struct drm_event drm_evdi_event_ddcci_data::base"

.PP
定義在 evdi_drm\&.h 檔案之第 100 行\&.
.SS "unsigned \fBchar\fP drm_evdi_event_ddcci_data::buffer[\fBDDCCI_BUFFER_SIZE\fP]"

.PP
定義在 evdi_drm\&.h 檔案之第 107 行\&.
.SS "uint32_t drm_evdi_event_ddcci_data::buffer_length"

.PP
定義在 evdi_drm\&.h 檔案之第 108 行\&.
.SS "uint16_t drm_evdi_event_ddcci_data::flags"

.PP
定義在 evdi_drm\&.h 檔案之第 109 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
