.TH "drm_evdi_event_cursor_set" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drm_evdi_event_cursor_set
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <evdi_drm\&.h>\fP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "struct drm_event \fBbase\fP"
.br
.ti -1c
.RI "int32_t \fBhot_x\fP"
.br
.ti -1c
.RI "int32_t \fBhot_y\fP"
.br
.ti -1c
.RI "uint32_t \fBwidth\fP"
.br
.ti -1c
.RI "uint32_t \fBheight\fP"
.br
.ti -1c
.RI "uint8_t \fBenabled\fP"
.br
.ti -1c
.RI "uint32_t \fBbuffer_handle\fP"
.br
.ti -1c
.RI "uint32_t \fBbuffer_length\fP"
.br
.ti -1c
.RI "uint32_t \fBpixel_format\fP"
.br
.ti -1c
.RI "uint32_t \fBstride\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 evdi_drm\&.h 檔案之第 73 行\&.
.SH "資料成員說明文件"
.PP 
.SS "struct drm_event drm_evdi_event_cursor_set::base"

.PP
定義在 evdi_drm\&.h 檔案之第 70 行\&.
.SS "uint32_t drm_evdi_event_cursor_set::buffer_handle"

.PP
定義在 evdi_drm\&.h 檔案之第 80 行\&.
.SS "uint32_t drm_evdi_event_cursor_set::buffer_length"

.PP
定義在 evdi_drm\&.h 檔案之第 81 行\&.
.SS "uint8_t drm_evdi_event_cursor_set::enabled"

.PP
定義在 evdi_drm\&.h 檔案之第 79 行\&.
.SS "uint32_t drm_evdi_event_cursor_set::height"

.PP
定義在 evdi_drm\&.h 檔案之第 78 行\&.
.SS "int32_t drm_evdi_event_cursor_set::hot_x"

.PP
定義在 evdi_drm\&.h 檔案之第 75 行\&.
.SS "int32_t drm_evdi_event_cursor_set::hot_y"

.PP
定義在 evdi_drm\&.h 檔案之第 76 行\&.
.SS "uint32_t drm_evdi_event_cursor_set::pixel_format"

.PP
定義在 evdi_drm\&.h 檔案之第 82 行\&.
.SS "uint32_t drm_evdi_event_cursor_set::stride"

.PP
定義在 evdi_drm\&.h 檔案之第 83 行\&.
.SS "uint32_t drm_evdi_event_cursor_set::width"

.PP
定義在 evdi_drm\&.h 檔案之第 77 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
