.TH "drm_evdi_ddcci_response" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drm_evdi_ddcci_response
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <evdi_drm\&.h>\fP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "const unsigned \fBchar\fP *\fB__user\fP \fBbuffer\fP"
.br
.ti -1c
.RI "uint32_t \fBbuffer_length\fP"
.br
.ti -1c
.RI "uint8_t \fBresult\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 evdi_drm\&.h 檔案之第 92 行\&.
.SH "資料成員說明文件"
.PP 
.SS "const unsigned \fBchar\fP* \fB__user\fP drm_evdi_ddcci_response::buffer"

.PP
定義在 evdi_drm\&.h 檔案之第 93 行\&.
.SS "uint32_t drm_evdi_ddcci_response::buffer_length"

.PP
定義在 evdi_drm\&.h 檔案之第 94 行\&.
.SS "uint8_t drm_evdi_ddcci_response::result"

.PP
定義在 evdi_drm\&.h 檔案之第 95 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
