.TH "/home/odin/Desktop/program/usbdisp_linux/libusbdisp/libenc/Encoder.cpp" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/odin/Desktop/program/usbdisp_linux/libusbdisp/libenc/Encoder.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include 'Encoder\&.h'\fP
.br
\fC#include <malloc\&.h>\fP
.br

.SS "複合項目"

.in +1c
.ti -1c
.RI "struct \fBblockheader_t\fP"
.br
.in -1c
.SS "定義"

.in +1c
.ti -1c
.RI "#define \fBPROCESS_BLOCKS\fP   (\fBMAX_SCREEN_BLOCK\fP/\fBENC_THREADS\fP)"
.br
.in -1c
.SH "定義巨集說明文件"
.PP 
.SS "#define PROCESS_BLOCKS   (\fBMAX_SCREEN_BLOCK\fP/\fBENC_THREADS\fP)"

.PP
定義在 Encoder\&.cpp 檔案之第 143 行\&.
.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
