.TH "/home/odin/Desktop/program/usbdisp_linux/libusbdisp/libenc/EncodeEngine.cpp" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/odin/Desktop/program/usbdisp_linux/libusbdisp/libenc/EncodeEngine.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <unistd\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <malloc\&.h>\fP
.br
\fC#include 'EncodeEngine\&.h'\fP
.br
\fC#include 'debug_trace\&.h'\fP
.br

.SS "變數"

.in +1c
.ti -1c
.RI "\fBevent_t\fP \fBsync_event\fP"
.br
.in -1c
.SH "變數說明文件"
.PP 
.SS "\fBevent_t\fP sync_event"

.PP
定義在 EncodeEngine\&.cpp 檔案之第 10 行\&.
.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
