.TH "/home/odin/Desktop/program/usbdisp_linux/libusbdisp/deb_install/com.racertech.usbdisp-1.0.0/opt/apps/com.racertech.usbdisp/files/evdi/module/evdi_sysfs.h" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/odin/Desktop/program/usbdisp_linux/libusbdisp/deb_install/com.racertech.usbdisp-1.0.0/opt/apps/com.racertech.usbdisp/files/evdi/module/evdi_sysfs.h
.SH SYNOPSIS
.br
.PP
.SS "函式"

.in +1c
.ti -1c
.RI "void \fBevdi_sysfs_init\fP (struct device *root)"
.br
.ti -1c
.RI "void \fBevdi_sysfs_exit\fP (struct device *root)"
.br
.in -1c
.SH "函式說明文件"
.PP 
.SS "void evdi_sysfs_exit (struct device * root)"

.PP
定義在 evdi_sysfs\&.c 檔案之第 245 行\&.
.SS "void evdi_sysfs_init (struct device * root)"

.PP
定義在 evdi_sysfs\&.c 檔案之第 236 行\&.
.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
