.TH "/home/odin/Desktop/program/usbdisp_linux/libusbdisp/deb_install/com.racertech.usbdisp-1.0.0/opt/apps/com.racertech.usbdisp/files/evdi/module/evdi_modeset.c" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/odin/Desktop/program/usbdisp_linux/libusbdisp/deb_install/com.racertech.usbdisp-1.0.0/opt/apps/com.racertech.usbdisp/files/evdi/module/evdi_modeset.c
.SH SYNOPSIS
.br
.PP
\fC#include <linux/version\&.h>\fP
.br
\fC#include <drm/drm_vblank\&.h>\fP
.br
\fC#include <drm/drm_damage_helper\&.h>\fP
.br
\fC#include <drm/drm_atomic\&.h>\fP
.br
\fC#include <drm/drm_crtc\&.h>\fP
.br
\fC#include <drm/drm_crtc_helper\&.h>\fP
.br
\fC#include <drm/drm_plane_helper\&.h>\fP
.br
\fC#include <drm/drm_atomic_helper\&.h>\fP
.br
\fC#include 'evdi_drm\&.h'\fP
.br
\fC#include 'evdi_drm_drv\&.h'\fP
.br
\fC#include 'evdi_cursor\&.h'\fP
.br
\fC#include 'evdi_params\&.h'\fP
.br
\fC#include <drm/drm_gem_atomic_helper\&.h>\fP
.br

.SS "函式"

.in +1c
.ti -1c
.RI "void \fBevdi_modeset_init\fP (struct drm_device *dev)"
.br
.ti -1c
.RI "void \fBevdi_modeset_cleanup\fP (__maybe_unused struct drm_device *dev)"
.br
.in -1c
.SH "函式說明文件"
.PP 
.SS "void evdi_modeset_cleanup (__maybe_unused struct drm_device * dev)"

.PP
定義在 evdi_modeset\&.c 檔案之第 539 行\&.
.SS "void evdi_modeset_init (struct drm_device * dev)"

.PP
定義在 evdi_modeset\&.c 檔案之第 511 行\&.
.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
