.TH "/home/odin/Desktop/program/usbdisp_linux/libusbdisp/deb_install/com.racertech.usbdisp-1.0.0/opt/apps/com.racertech.usbdisp/files/evdi/module/evdi_params.h" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/odin/Desktop/program/usbdisp_linux/libusbdisp/deb_install/com.racertech.usbdisp-1.0.0/opt/apps/com.racertech.usbdisp/files/evdi/module/evdi_params.h
.SH SYNOPSIS
.br
.PP
.SS "變數"

.in +1c
.ti -1c
.RI "unsigned \fBint\fP \fBevdi_loglevel\fP"
.br
.ti -1c
.RI "unsigned \fBshort\fP \fBint\fP \fBevdi_initial_device_count\fP"
.br
.in -1c
.SH "變數說明文件"
.PP 
.SS "unsigned \fBshort\fP \fBint\fP evdi_initial_device_count\fC [extern]\fP"

.SS "unsigned \fBint\fP evdi_loglevel\fC [extern]\fP"

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
