.TH "evdi_mode" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
evdi_mode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <evdi_lib\&.h>\fP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "\fBint\fP \fBwidth\fP"
.br
.ti -1c
.RI "\fBint\fP \fBheight\fP"
.br
.ti -1c
.RI "\fBint\fP \fBrefresh_rate\fP"
.br
.ti -1c
.RI "\fBint\fP \fBbits_per_pixel\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBpixel_format\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 evdi_lib\&.h 檔案之第 38 行\&.
.SH "資料成員說明文件"
.PP 
.SS "\fBint\fP evdi_mode::bits_per_pixel"

.PP
定義在 evdi_lib\&.h 檔案之第 42 行\&.
.SS "\fBint\fP evdi_mode::height"

.PP
定義在 evdi_lib\&.h 檔案之第 40 行\&.
.SS "unsigned \fBint\fP evdi_mode::pixel_format"

.PP
定義在 evdi_lib\&.h 檔案之第 43 行\&.
.SS "\fBint\fP evdi_mode::refresh_rate"

.PP
定義在 evdi_lib\&.h 檔案之第 41 行\&.
.SS "\fBint\fP evdi_mode::width"

.PP
定義在 evdi_lib\&.h 檔案之第 39 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
