.TH "/home/odin/Desktop/program/usbdisp_linux/libusbdisp/deb_install/com.racertech.usbdisp-1.0.0/opt/apps/com.racertech.usbdisp/files/evdi/module/evdi_sysfs.c" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/odin/Desktop/program/usbdisp_linux/libusbdisp/deb_install/com.racertech.usbdisp-1.0.0/opt/apps/com.racertech.usbdisp/files/evdi/module/evdi_sysfs.c
.SH SYNOPSIS
.br
.PP
\fC#include <linux/device\&.h>\fP
.br
\fC#include <linux/slab\&.h>\fP
.br
\fC#include <linux/usb\&.h>\fP
.br
\fC#include 'evdi_sysfs\&.h'\fP
.br
\fC#include 'evdi_params\&.h'\fP
.br
\fC#include 'evdi_debug\&.h'\fP
.br
\fC#include 'evdi_platform_drv\&.h'\fP
.br

.SS "複合項目"

.in +1c
.ti -1c
.RI "struct \fBevdi_usb_addr\fP"
.br
.in -1c
.SS "定義"

.in +1c
.ti -1c
.RI "#define \fBMAX_EVDI_USB_ADDR\fP   10"
.br
.in -1c
.SS "函式"

.in +1c
.ti -1c
.RI "void \fBevdi_sysfs_init\fP (struct device *root)"
.br
.ti -1c
.RI "void \fBevdi_sysfs_exit\fP (struct device *root)"
.br
.in -1c
.SH "定義巨集說明文件"
.PP 
.SS "#define MAX_EVDI_USB_ADDR   10"

.PP
定義在 evdi_sysfs\&.c 檔案之第 31 行\&.
.SH "函式說明文件"
.PP 
.SS "void evdi_sysfs_exit (struct device * root)"

.PP
定義在 evdi_sysfs\&.c 檔案之第 245 行\&.
.SS "void evdi_sysfs_init (struct device * root)"

.PP
定義在 evdi_sysfs\&.c 檔案之第 236 行\&.
.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
