.TH "/home/odin/Desktop/program/usbdisp_linux/libusbdisp/deb_install/com.racertech.usbdisp-1.0.0/opt/apps/com.racertech.usbdisp/files/evdi/module/evdi_platform_drv.h" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/odin/Desktop/program/usbdisp_linux/libusbdisp/deb_install/com.racertech.usbdisp-1.0.0/opt/apps/com.racertech.usbdisp/files/evdi/module/evdi_platform_drv.h
.SH SYNOPSIS
.br
.PP
.SS "定義"

.in +1c
.ti -1c
.RI "#define \fBDRIVER_NAME\fP   'evdi'"
.br
.ti -1c
.RI "#define \fBDRIVER_DESC\fP   'Extensible Virtual Display Interface'"
.br
.ti -1c
.RI "#define \fBDRIVER_DATE\fP   '20220713'"
.br
.ti -1c
.RI "#define \fBDRIVER_MAJOR\fP   1"
.br
.ti -1c
.RI "#define \fBDRIVER_MINOR\fP   12"
.br
.ti -1c
.RI "#define \fBDRIVER_PATCH\fP   0"
.br
.in -1c
.SS "函式"

.in +1c
.ti -1c
.RI "void \fBevdi_platform_remove_all_devices\fP (struct device *device)"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBevdi_platform_device_count\fP (struct device *device)"
.br
.ti -1c
.RI "\fBint\fP \fBevdi_platform_add_devices\fP (struct device *device, unsigned \fBint\fP val)"
.br
.ti -1c
.RI "\fBint\fP \fBevdi_platform_device_add\fP (struct device *device, struct device *parent)"
.br
.in -1c
.SH "定義巨集說明文件"
.PP 
.SS "#define DRIVER_DATE   '20220713'"

.PP
定義在 evdi_platform_drv\&.h 檔案之第 28 行\&.
.SS "#define DRIVER_DESC   'Extensible Virtual Display Interface'"

.PP
定義在 evdi_platform_drv\&.h 檔案之第 27 行\&.
.SS "#define DRIVER_MAJOR   1"

.PP
定義在 evdi_platform_drv\&.h 檔案之第 30 行\&.
.SS "#define DRIVER_MINOR   12"

.PP
定義在 evdi_platform_drv\&.h 檔案之第 31 行\&.
.SS "#define DRIVER_NAME   'evdi'"

.PP
定義在 evdi_platform_drv\&.h 檔案之第 26 行\&.
.SS "#define DRIVER_PATCH   0"

.PP
定義在 evdi_platform_drv\&.h 檔案之第 32 行\&.
.SH "函式說明文件"
.PP 
.SS "\fBint\fP evdi_platform_add_devices (struct device * device, unsigned \fBint\fP val)"

.PP
定義在 evdi_platform_drv\&.c 檔案之第 145 行\&.
.SS "\fBint\fP evdi_platform_device_add (struct device * device, struct device * parent)"

.PP
定義在 evdi_platform_drv\&.c 檔案之第 124 行\&.
.SS "unsigned \fBint\fP evdi_platform_device_count (struct device * device)"

.PP
定義在 evdi_platform_drv\&.c 檔案之第 183 行\&.
.SS "void evdi_platform_remove_all_devices (struct device * device)"

.PP
定義在 evdi_platform_drv\&.c 檔案之第 164 行\&.
.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
