.TH "evdi_event_mode_changed_pending" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
evdi_event_mode_changed_pending
.SH SYNOPSIS
.br
.PP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "struct drm_pending_event \fBbase\fP"
.br
.ti -1c
.RI "struct \fBdrm_evdi_event_mode_changed\fP \fBmode_changed\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 evdi_painter\&.c 檔案之第 62 行\&.
.SH "資料成員說明文件"
.PP 
.SS "struct drm_pending_event evdi_event_mode_changed_pending::base"

.PP
定義在 evdi_painter\&.c 檔案之第 1367 行\&.
.SS "struct \fBdrm_evdi_event_mode_changed\fP evdi_event_mode_changed_pending::mode_changed"

.PP
定義在 evdi_painter\&.c 檔案之第 1367 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
