.TH "/home/odin/Desktop/program/usbdisp_linux/libusbdisp/deb_install/com.racertech.usbdisp-1.0.0/opt/apps/com.racertech.usbdisp/files/evdi/module/evdi_debug.c" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/odin/Desktop/program/usbdisp_linux/libusbdisp/deb_install/com.racertech.usbdisp-1.0.0/opt/apps/com.racertech.usbdisp/files/evdi/module/evdi_debug.c
.SH SYNOPSIS
.br
.PP
\fC#include <linux/sched\&.h>\fP
.br
\fC#include 'evdi_debug\&.h'\fP
.br

.SS "函式"

.in +1c
.ti -1c
.RI "void \fBevdi_log_process\fP (\fBchar\fP *buf, size_t size)"
.br
.in -1c
.SH "函式說明文件"
.PP 
.SS "void evdi_log_process (\fBchar\fP * buf, size_t size)"

.PP
定義在 evdi_debug\&.c 檔案之第 13 行\&.
.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
