.TH "evdi_framebuffer" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
evdi_framebuffer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <evdi_drm_drv\&.h>\fP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "struct drm_framebuffer \fBbase\fP"
.br
.ti -1c
.RI "struct \fBevdi_gem_object\fP * \fBobj\fP"
.br
.ti -1c
.RI "bool \fBactive\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 evdi_drm_drv\&.h 檔案之第 86 行\&.
.SH "資料成員說明文件"
.PP 
.SS "bool evdi_framebuffer::active"

.PP
定義在 evdi_drm_drv\&.h 檔案之第 89 行\&.
.SS "struct drm_framebuffer evdi_framebuffer::base"

.PP
定義在 evdi_drm_drv\&.h 檔案之第 81 行\&.
.SS "struct \fBevdi_gem_object\fP* evdi_framebuffer::obj"

.PP
定義在 evdi_drm_drv\&.h 檔案之第 88 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
