.TH "/home/odin/Desktop/program/usbdisp_linux/libusbdisp/deb_install/com.racertech.usbdisp-1.0.0/opt/apps/com.racertech.usbdisp/files/evdi/module/evdi_i2c.c" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/odin/Desktop/program/usbdisp_linux/libusbdisp/deb_install/com.racertech.usbdisp-1.0.0/opt/apps/com.racertech.usbdisp/files/evdi/module/evdi_i2c.c
.SH SYNOPSIS
.br
.PP
\fC#include 'evdi_i2c\&.h'\fP
.br
\fC#include 'evdi_debug\&.h'\fP
.br
\fC#include 'evdi_drm_drv\&.h'\fP
.br

.SS "函式"

.in +1c
.ti -1c
.RI "\fBint\fP \fBevdi_i2c_add\fP (struct i2c_adapter *adapter, struct device *parent, void *ddev)"
.br
.ti -1c
.RI "void \fBevdi_i2c_remove\fP (struct i2c_adapter *adapter)"
.br
.in -1c
.SH "函式說明文件"
.PP 
.SS "\fBint\fP evdi_i2c_add (struct i2c_adapter * adapter, struct device * parent, void * ddev)"

.PP
定義在 evdi_i2c\&.c 檔案之第 39 行\&.
.SS "void evdi_i2c_remove (struct i2c_adapter * adapter)"

.PP
定義在 evdi_i2c\&.c 檔案之第 52 行\&.
.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
