.TH "evdi_cursor" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
evdi_cursor
.SH SYNOPSIS
.br
.PP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "bool \fBenabled\fP"
.br
.ti -1c
.RI "int32_t \fBx\fP"
.br
.ti -1c
.RI "int32_t \fBy\fP"
.br
.ti -1c
.RI "uint32_t \fBwidth\fP"
.br
.ti -1c
.RI "uint32_t \fBheight\fP"
.br
.ti -1c
.RI "int32_t \fBhot_x\fP"
.br
.ti -1c
.RI "int32_t \fBhot_y\fP"
.br
.ti -1c
.RI "uint32_t \fBpixel_format\fP"
.br
.ti -1c
.RI "uint32_t \fBstride\fP"
.br
.ti -1c
.RI "struct \fBevdi_gem_object\fP * \fBobj\fP"
.br
.ti -1c
.RI "struct mutex \fBlock\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 evdi_cursor\&.c 檔案之第 38 行\&.
.SH "資料成員說明文件"
.PP 
.SS "bool evdi_cursor::enabled"

.PP
定義在 evdi_cursor\&.c 檔案之第 39 行\&.
.SS "uint32_t evdi_cursor::height"

.PP
定義在 evdi_cursor\&.c 檔案之第 43 行\&.
.SS "int32_t evdi_cursor::hot_x"

.PP
定義在 evdi_cursor\&.c 檔案之第 44 行\&.
.SS "int32_t evdi_cursor::hot_y"

.PP
定義在 evdi_cursor\&.c 檔案之第 45 行\&.
.SS "struct mutex evdi_cursor::lock"

.PP
定義在 evdi_cursor\&.c 檔案之第 48 行\&.
.SS "struct \fBevdi_gem_object\fP* evdi_cursor::obj"

.PP
定義在 evdi_cursor\&.c 檔案之第 48 行\&.
.SS "uint32_t evdi_cursor::pixel_format"

.PP
定義在 evdi_cursor\&.c 檔案之第 46 行\&.
.SS "uint32_t evdi_cursor::stride"

.PP
定義在 evdi_cursor\&.c 檔案之第 47 行\&.
.SS "uint32_t evdi_cursor::width"

.PP
定義在 evdi_cursor\&.c 檔案之第 42 行\&.
.SS "int32_t evdi_cursor::x"

.PP
定義在 evdi_cursor\&.c 檔案之第 40 行\&.
.SS "int32_t evdi_cursor::y"

.PP
定義在 evdi_cursor\&.c 檔案之第 41 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
