.TH "/home/odin/Desktop/program/usbdisp_linux/libusbdisp/deb_install/com.racertech.usbdisp-1.0.0/opt/apps/com.racertech.usbdisp/files/evdi/module/evdi_encoder.c" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/odin/Desktop/program/usbdisp_linux/libusbdisp/deb_install/com.racertech.usbdisp-1.0.0/opt/apps/com.racertech.usbdisp/files/evdi/module/evdi_encoder.c
.SH SYNOPSIS
.br
.PP
\fC#include <linux/version\&.h>\fP
.br
\fC#include <drm/drm_crtc\&.h>\fP
.br
\fC#include <drm/drm_crtc_helper\&.h>\fP
.br
\fC#include 'evdi_drm_drv\&.h'\fP
.br

.SS "函式"

.in +1c
.ti -1c
.RI "struct drm_encoder * \fBevdi_encoder_init\fP (struct drm_device *dev)"
.br
.in -1c
.SH "函式說明文件"
.PP 
.SS "struct drm_encoder* evdi_encoder_init (struct drm_device * dev)"

.PP
定義在 evdi_encoder\&.c 檔案之第 47 行\&.
.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
