.TH "/home/odin/Desktop/program/usbdisp_linux/libusbdisp/deb_install/com.racertech.usbdisp-1.0.0/opt/apps/com.racertech.usbdisp/files/evdi/module/evdi_connector.c" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/odin/Desktop/program/usbdisp_linux/libusbdisp/deb_install/com.racertech.usbdisp-1.0.0/opt/apps/com.racertech.usbdisp/files/evdi/module/evdi_connector.c
.SH SYNOPSIS
.br
.PP
\fC#include <linux/version\&.h>\fP
.br
\fC#include <drm/drm_crtc\&.h>\fP
.br
\fC#include <drm/drm_edid\&.h>\fP
.br
\fC#include <drm/drm_crtc_helper\&.h>\fP
.br
\fC#include <drm/drm_atomic_helper\&.h>\fP
.br
\fC#include 'evdi_drm_drv\&.h'\fP
.br
\fC#include <drm/drm_probe_helper\&.h>\fP
.br

.SS "函式"

.in +1c
.ti -1c
.RI "\fBint\fP \fBevdi_connector_init\fP (struct drm_device *dev, struct drm_encoder *encoder)"
.br
.in -1c
.SH "函式說明文件"
.PP 
.SS "\fBint\fP evdi_connector_init (struct drm_device * dev, struct drm_encoder * encoder)"

.PP
定義在 evdi_connector\&.c 檔案之第 143 行\&.
.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
