.TH "evdi_frame_buffer_node" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
evdi_frame_buffer_node
.SH SYNOPSIS
.br
.PP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "struct \fBevdi_buffer\fP \fBframe_buffer\fP"
.br
.ti -1c
.RI "struct \fBevdi_frame_buffer_node\fP * \fBnext\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 evdi_lib\&.c 檔案之第 50 行\&.
.SH "資料成員說明文件"
.PP 
.SS "struct \fBevdi_buffer\fP evdi_frame_buffer_node::frame_buffer"

.PP
定義在 evdi_lib\&.c 檔案之第 1015 行\&.
.SS "struct \fBevdi_frame_buffer_node\fP* evdi_frame_buffer_node::next"

.PP
定義在 evdi_lib\&.c 檔案之第 52 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
