.TH "evdi_ddcci_data" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
evdi_ddcci_data
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <evdi_lib\&.h>\fP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "uint16_t \fBaddress\fP"
.br
.ti -1c
.RI "uint16_t \fBflags\fP"
.br
.ti -1c
.RI "uint32_t \fBbuffer_length\fP"
.br
.ti -1c
.RI "uint8_t * \fBbuffer\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 evdi_lib\&.h 檔案之第 74 行\&.
.SH "資料成員說明文件"
.PP 
.SS "uint16_t evdi_ddcci_data::address"

.PP
定義在 evdi_lib\&.h 檔案之第 75 行\&.
.SS "uint8_t* evdi_ddcci_data::buffer"

.PP
定義在 evdi_lib\&.h 檔案之第 78 行\&.
.SS "uint32_t evdi_ddcci_data::buffer_length"

.PP
定義在 evdi_lib\&.h 檔案之第 77 行\&.
.SS "uint16_t evdi_ddcci_data::flags"

.PP
定義在 evdi_lib\&.h 檔案之第 76 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
