.TH "evdi_buffer" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
evdi_buffer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <evdi_lib\&.h>\fP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "\fBint\fP \fBid\fP"
.br
.ti -1c
.RI "void * \fBbuffer\fP"
.br
.ti -1c
.RI "\fBint\fP \fBwidth\fP"
.br
.ti -1c
.RI "\fBint\fP \fBheight\fP"
.br
.ti -1c
.RI "\fBint\fP \fBstride\fP"
.br
.ti -1c
.RI "struct \fBevdi_rect\fP * \fBrects\fP"
.br
.ti -1c
.RI "\fBint\fP \fBrect_count\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 evdi_lib\&.h 檔案之第 46 行\&.
.SH "資料成員說明文件"
.PP 
.SS "void* evdi_buffer::buffer"

.PP
定義在 evdi_lib\&.h 檔案之第 48 行\&.
.SS "\fBint\fP evdi_buffer::height"

.PP
定義在 evdi_lib\&.h 檔案之第 50 行\&.
.SS "\fBint\fP evdi_buffer::id"

.PP
定義在 evdi_lib\&.h 檔案之第 47 行\&.
.SS "\fBint\fP evdi_buffer::rect_count"

.PP
定義在 evdi_lib\&.h 檔案之第 54 行\&.
.SS "struct \fBevdi_rect\fP* evdi_buffer::rects"

.PP
定義在 evdi_lib\&.h 檔案之第 53 行\&.
.SS "\fBint\fP evdi_buffer::stride"

.PP
定義在 evdi_lib\&.h 檔案之第 51 行\&.
.SS "\fBint\fP evdi_buffer::width"

.PP
定義在 evdi_lib\&.h 檔案之第 49 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
