.TH "evdi_rect" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
evdi_rect
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <evdi_lib\&.h>\fP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "\fBint\fP \fBx1\fP"
.br
.ti -1c
.RI "\fBint\fP \fBy1\fP"
.br
.ti -1c
.RI "\fBint\fP \fBx2\fP"
.br
.ti -1c
.RI "\fBint\fP \fBy2\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 evdi_lib\&.h 檔案之第 34 行\&.
.SH "資料成員說明文件"
.PP 
.SS "\fBint\fP evdi_rect::x1"

.PP
定義在 evdi_lib\&.h 檔案之第 35 行\&.
.SS "\fBint\fP evdi_rect::x2"

.PP
定義在 evdi_lib\&.h 檔案之第 35 行\&.
.SS "\fBint\fP evdi_rect::y1"

.PP
定義在 evdi_lib\&.h 檔案之第 35 行\&.
.SS "\fBint\fP evdi_rect::y2"

.PP
定義在 evdi_lib\&.h 檔案之第 35 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
