.TH "evdi_platform_device_data" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
evdi_platform_device_data
.SH SYNOPSIS
.br
.PP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "struct drm_device * \fBdrm_dev\fP"
.br
.ti -1c
.RI "struct device * \fBparent\fP"
.br
.ti -1c
.RI "bool \fBsymlinked\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 evdi_platform_dev\&.c 檔案之第 32 行\&.
.SH "資料成員說明文件"
.PP 
.SS "struct drm_device* evdi_platform_device_data::drm_dev"

.PP
定義在 evdi_platform_dev\&.c 檔案之第 33 行\&.
.SS "struct device* evdi_platform_device_data::parent"

.PP
定義在 evdi_platform_dev\&.c 檔案之第 34 行\&.
.SS "bool evdi_platform_device_data::symlinked"

.PP
定義在 evdi_platform_dev\&.c 檔案之第 35 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
