.TH "evdi_device_context" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
evdi_device_context
.SH SYNOPSIS
.br
.PP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "\fBint\fP \fBfd\fP"
.br
.ti -1c
.RI "\fBint\fP \fBbufferToUpdate\fP"
.br
.ti -1c
.RI "struct \fBevdi_frame_buffer_node\fP * \fBframeBuffersListHead\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdevice_index\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 evdi_lib\&.c 檔案之第 55 行\&.
.SH "資料成員說明文件"
.PP 
.SS "\fBint\fP evdi_device_context::bufferToUpdate"

.PP
定義在 evdi_lib\&.c 檔案之第 57 行\&.
.SS "\fBint\fP evdi_device_context::device_index"

.PP
定義在 evdi_lib\&.c 檔案之第 59 行\&.
.SS "\fBint\fP evdi_device_context::fd"

.PP
定義在 evdi_lib\&.c 檔案之第 56 行\&.
.SS "struct \fBevdi_frame_buffer_node\fP* evdi_device_context::frameBuffersListHead"

.PP
定義在 evdi_lib\&.c 檔案之第 58 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
