.TH "evdi_cursor_set" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
evdi_cursor_set
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <evdi_lib\&.h>\fP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "int32_t \fBhot_x\fP"
.br
.ti -1c
.RI "int32_t \fBhot_y\fP"
.br
.ti -1c
.RI "uint32_t \fBwidth\fP"
.br
.ti -1c
.RI "uint32_t \fBheight\fP"
.br
.ti -1c
.RI "uint8_t \fBenabled\fP"
.br
.ti -1c
.RI "uint32_t \fBbuffer_length\fP"
.br
.ti -1c
.RI "uint32_t * \fBbuffer\fP"
.br
.ti -1c
.RI "uint32_t \fBpixel_format\fP"
.br
.ti -1c
.RI "uint32_t \fBstride\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 evdi_lib\&.h 檔案之第 57 行\&.
.SH "資料成員說明文件"
.PP 
.SS "uint32_t* evdi_cursor_set::buffer"

.PP
定義在 evdi_lib\&.h 檔案之第 64 行\&.
.SS "uint32_t evdi_cursor_set::buffer_length"

.PP
定義在 evdi_lib\&.h 檔案之第 63 行\&.
.SS "uint8_t evdi_cursor_set::enabled"

.PP
定義在 evdi_lib\&.h 檔案之第 62 行\&.
.SS "uint32_t evdi_cursor_set::height"

.PP
定義在 evdi_lib\&.h 檔案之第 61 行\&.
.SS "int32_t evdi_cursor_set::hot_x"

.PP
定義在 evdi_lib\&.h 檔案之第 58 行\&.
.SS "int32_t evdi_cursor_set::hot_y"

.PP
定義在 evdi_lib\&.h 檔案之第 59 行\&.
.SS "uint32_t evdi_cursor_set::pixel_format"

.PP
定義在 evdi_lib\&.h 檔案之第 65 行\&.
.SS "uint32_t evdi_cursor_set::stride"

.PP
定義在 evdi_lib\&.h 檔案之第 66 行\&.
.SS "uint32_t evdi_cursor_set::width"

.PP
定義在 evdi_lib\&.h 檔案之第 60 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
