.TH "evdi_usb_addr" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
evdi_usb_addr
.SH SYNOPSIS
.br
.PP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "\fBint\fP \fBaddr\fP [\fBMAX_EVDI_USB_ADDR\fP]"
.br
.ti -1c
.RI "\fBint\fP \fBlen\fP"
.br
.ti -1c
.RI "struct usb_device * \fBusb\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 evdi_sysfs\&.c 檔案之第 48 行\&.
.SH "資料成員說明文件"
.PP 
.SS "\fBint\fP evdi_usb_addr::addr[\fBMAX_EVDI_USB_ADDR\fP]"

.PP
定義在 evdi_sysfs\&.c 檔案之第 49 行\&.
.SS "\fBint\fP evdi_usb_addr::len"

.PP
定義在 evdi_sysfs\&.c 檔案之第 50 行\&.
.SS "struct usb_device* evdi_usb_addr::usb"

.PP
定義在 evdi_sysfs\&.c 檔案之第 51 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
