.TH "evdi_logging" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
evdi_logging
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <evdi_lib\&.h>\fP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "void(* \fBfunction\fP )(void *\fBuser_data\fP, const \fBchar\fP *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void * \fBuser_data\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 evdi_lib\&.h 檔案之第 95 行\&.
.SH "資料成員說明文件"
.PP 
.SS "void(* evdi_logging::function) (void *\fBuser_data\fP, const \fBchar\fP *fmt,\&.\&.\&.)"

.PP
定義在 evdi_lib\&.h 檔案之第 96 行\&.
.SS "void* evdi_logging::user_data"

.PP
定義在 evdi_lib\&.h 檔案之第 97 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
