.TH "/home/odin/Desktop/program/usbdisp_linux/libusbdisp/libenc/event.h" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/odin/Desktop/program/usbdisp_linux/libusbdisp/libenc/event.h
.SH SYNOPSIS
.br
.PP
\fC#include <pthread\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br

.SS "複合項目"

.in +1c
.ti -1c
.RI "struct \fBevent_t\fP"
.br
.in -1c
.SS "定義"

.in +1c
.ti -1c
.RI "#define \fBSetEvent\fP(event)   \fBset_event\fP(&(event))"
.br
.ti -1c
.RI "#define \fBWaitEvent\fP(event)   \fBwait_event\fP(&(event))"
.br
.in -1c
.SS "函式"

.in +1c
.ti -1c
.RI "void \fBinit_event\fP (\fBevent_t\fP *event)"
.br
.ti -1c
.RI "void \fBuninit_event\fP (\fBevent_t\fP *event)"
.br
.ti -1c
.RI "void \fBset_event\fP (\fBevent_t\fP *event)"
.br
.ti -1c
.RI "void \fBwait_event\fP (\fBevent_t\fP *event)"
.br
.ti -1c
.RI "\fBint\fP \fBtime_wait_event\fP (\fBevent_t\fP *event, \fBint\fP ms)"
.br
.in -1c
.SH "定義巨集說明文件"
.PP 
.SS "#define SetEvent(event)   \fBset_event\fP(&(event))"

.PP
定義在 event\&.h 檔案之第 17 行\&.
.SS "#define WaitEvent(event)   \fBwait_event\fP(&(event))"

.PP
定義在 event\&.h 檔案之第 18 行\&.
.SH "函式說明文件"
.PP 
.SS "void init_event (\fBevent_t\fP * event)"

.PP
定義在 event\&.c 檔案之第 6 行\&.
.SS "void set_event (\fBevent_t\fP * event)"

.PP
定義在 event\&.c 檔案之第 19 行\&.
.SS "\fBint\fP time_wait_event (\fBevent_t\fP * event, \fBint\fP ms)"

.PP
定義在 event\&.c 檔案之第 40 行\&.
.SS "void uninit_event (\fBevent_t\fP * event)"

.PP
定義在 event\&.c 檔案之第 13 行\&.
.SS "void wait_event (\fBevent_t\fP * event)"

.PP
定義在 event\&.c 檔案之第 28 行\&.
.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
