.TH "HuffmanTable_t" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HuffmanTable_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jpeg_enc\&.h>\fP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "\fBbitstring\fP \fBDC\fP [12]"
.br
.ti -1c
.RI "\fBbitstring\fP \fBAC\fP [256]"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 jpeg_enc\&.h 檔案之第 165 行\&.
.SH "資料成員說明文件"
.PP 
.SS "\fBbitstring\fP HuffmanTable_t::AC[256]"

.PP
定義在 jpeg_enc\&.h 檔案之第 167 行\&.
.SS "\fBbitstring\fP HuffmanTable_t::DC[12]"

.PP
定義在 jpeg_enc\&.h 檔案之第 166 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
