.TH "idtable_t" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
idtable_t
.SH SYNOPSIS
.br
.PP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "\fBint\fP \fBInterface\fP"
.br
.ti -1c
.RI "\fBint\fP \fBEndPoint\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 usbdev\&.cpp 檔案之第 8 行\&.
.SH "資料成員說明文件"
.PP 
.SS "\fBint\fP idtable_t::EndPoint"

.PP
定義在 usbdev\&.cpp 檔案之第 10 行\&.
.SS "\fBint\fP idtable_t::Interface"

.PP
定義在 usbdev\&.cpp 檔案之第 9 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
