.TH "jpeg_stream_t" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpeg_stream_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jpeg_enc\&.h>\fP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "unsigned \fBchar\fP * \fBpbitstream\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBpos\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 jpeg_enc\&.h 檔案之第 170 行\&.
.SH "資料成員說明文件"
.PP 
.SS "unsigned \fBchar\fP* jpeg_stream_t::pbitstream"

.PP
定義在 jpeg_enc\&.h 檔案之第 171 行\&.
.SS "unsigned \fBint\fP jpeg_stream_t::pos"

.PP
定義在 jpeg_enc\&.h 檔案之第 172 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
