.TH "/home/odin/Desktop/program/usbdisp_linux/libusbdisp/main.c" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/odin/Desktop/program/usbdisp_linux/libusbdisp/main.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'usbDisplay\&.h'\fP
.br
\fC#include <malloc\&.h>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'xrandr\&.h'\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "函式"

.in +1c
.ti -1c
.RI "\fBint\fP \fBusbDisplay_init\fP ()"
.br
.ti -1c
.RI "\fBint\fP \fBmain\fP (\fBint\fP argc, \fBchar\fP **argv)"
.br
.in -1c
.SS "變數"

.in +1c
.ti -1c
.RI "\fBUsbDisplay\fP * \fBusbservice\fP"
.br
.ti -1c
.RI "libusb_device_handle * \fBhandle\fP = NULL"
.br
.in -1c
.SH "函式說明文件"
.PP 
.SS "\fBint\fP main (\fBint\fP argc, \fBchar\fP ** argv)"

.PP
定義在 main\&.c 檔案之第 204 行\&.
.SS "\fBint\fP usbDisplay_init ()"

.PP
定義在 main\&.c 檔案之第 121 行\&.
.SH "變數說明文件"
.PP 
.SS "libusb_device_handle* handle = NULL"

.PP
定義在 main\&.c 檔案之第 33 行\&.
.SS "\fBUsbDisplay\fP* usbservice"

.PP
定義在 main\&.c 檔案之第 29 行\&.
.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
