.TH "md__home_odin__desktop_program_usbdisp_linux_libusbdisp_deb_install_com_racertech_usbdisp_1_0_0_opt_apps_com_racertech_usbdisp_files_evdi_docs_index" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home_odin__desktop_program_usbdisp_linux_libusbdisp_deb_install_com_racertech_usbdisp_1_0_0_opt_apps_com_racertech_usbdisp_files_evdi_docs_index \- Introduction 
Extensible Virtual Display Interface (EVDI in short) is a software project that allows any userspace Linux program manage additional displays, and receive updates for them\&. This short document explains how to use EVDI library in your application\&.
.PP
For more details about EVDI project and the latest code, see the \fCproject page\fP on DisplayLink's GitHub\&.
.SH "Project origin"
.PP
EVDI is a project that was started by DisplayLink as a base for the development of DisplayLink's Display driver for Ubuntu Linux, driving all current generation, USB 3\&.0 Universal Docking Stations and USB Display Adapters\&.
.PP
However, it soon became apparent that we're making a generic interface that any other application could use - and that's when DisplayLink decided to open-source the code and push it to GitHub\&.
.PP
!!! info The interface of the library is still changing\&. Please treat the API as not yet stable - in terms of allowing the possibility that it can still be modified, and your clients may require matching updates\&. 
