.TH "md__home_odin__desktop_program_usbdisp_linux_libusbdisp__r_e_a_d_m_e" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home_odin__desktop_program_usbdisp_linux_libusbdisp__r_e_a_d_m_e \- Usb_display_Ubuntu 
sudo g++ -o usb-disp -I/usr/local/include/libusb-1\&.0 *\&.c *\&.cpp **/*\&.c **/*\&.cpp -L/usr/local/lib -lusb-1\&.0 -I libenc/ -I \&. libenc/simd/*\&.o -pthread -D \fISSE2\fP -I/usr/X11R6/include -I/usr/local/include -L/usr/X11R6/lib -L/usr/local/lib -lX11 -lXext -lpng
.PP
git merge --no-ff dev
.PP
git log --pretty=format: 'h : s' --graph 
