.TH "/home/odin/Desktop/program/usbdisp_linux/libusbdisp/libenc/mm_type.h" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/odin/Desktop/program/usbdisp_linux/libusbdisp/libenc/mm_type.h
.SH SYNOPSIS
.br
.PP
\fC#include <inttypes\&.h>\fP
.br

.SS "定義"

.in +1c
.ti -1c
.RI "#define \fBBOOL\fP   bool"
.br
.in -1c
.SS "型態定義"

.in +1c
.ti -1c
.RI "typedef unsigned \fBchar\fP \fBBYTE\fP"
.br
.ti -1c
.RI "typedef unsigned \fBshort\fP \fBint\fP \fBWORD\fP"
.br
.ti -1c
.RI "typedef unsigned \fBint\fP \fBDWORD\fP"
.br
.ti -1c
.RI "typedef int64_t \fBINT64\fP"
.br
.ti -1c
.RI "typedef uint64_t \fBUINT64\fP"
.br
.ti -1c
.RI "typedef unsigned \fBchar\fP \fBUCHAR\fP"
.br
.ti -1c
.RI "typedef unsigned long \fBULONG\fP"
.br
.ti -1c
.RI "typedef unsigned \fBshort\fP \fBUSHORT\fP"
.br
.ti -1c
.RI "typedef signed \fBchar\fP \fBSBYTE\fP"
.br
.ti -1c
.RI "typedef signed \fBshort\fP \fBSWORD\fP"
.br
.ti -1c
.RI "typedef signed \fBint\fP \fBSDWORD\fP"
.br
.ti -1c
.RI "typedef signed \fBshort\fP \fBINT16\fP"
.br
.ti -1c
.RI "typedef unsigned \fBshort\fP \fBUINT16\fP"
.br
.ti -1c
.RI "typedef signed \fBint\fP \fBINT32\fP"
.br
.ti -1c
.RI "typedef unsigned \fBint\fP \fBUINT32\fP"
.br
.in -1c
.SH "定義巨集說明文件"
.PP 
.SS "#define BOOL   bool"

.PP
定義在 mm_type\&.h 檔案之第 16 行\&.
.SH "型態定義說明文件"
.PP 
.SS "typedef unsigned \fBchar\fP \fBBYTE\fP"

.PP
定義在 mm_type\&.h 檔案之第 8 行\&.
.SS "typedef unsigned \fBint\fP \fBDWORD\fP"

.PP
定義在 mm_type\&.h 檔案之第 10 行\&.
.SS "typedef signed \fBshort\fP \fBINT16\fP"

.PP
定義在 mm_type\&.h 檔案之第 22 行\&.
.SS "typedef signed \fBint\fP \fBINT32\fP"

.PP
定義在 mm_type\&.h 檔案之第 24 行\&.
.SS "typedef int64_t \fBINT64\fP"

.PP
定義在 mm_type\&.h 檔案之第 11 行\&.
.SS "typedef signed \fBchar\fP \fBSBYTE\fP"

.PP
定義在 mm_type\&.h 檔案之第 19 行\&.
.SS "typedef signed \fBint\fP \fBSDWORD\fP"

.PP
定義在 mm_type\&.h 檔案之第 21 行\&.
.SS "typedef signed \fBshort\fP \fBSWORD\fP"

.PP
定義在 mm_type\&.h 檔案之第 20 行\&.
.SS "typedef unsigned \fBchar\fP \fBUCHAR\fP"

.PP
定義在 mm_type\&.h 檔案之第 13 行\&.
.SS "typedef unsigned \fBshort\fP \fBUINT16\fP"

.PP
定義在 mm_type\&.h 檔案之第 23 行\&.
.SS "typedef unsigned \fBint\fP \fBUINT32\fP"

.PP
定義在 mm_type\&.h 檔案之第 25 行\&.
.SS "typedef uint64_t \fBUINT64\fP"

.PP
定義在 mm_type\&.h 檔案之第 12 行\&.
.SS "typedef unsigned long \fBULONG\fP"

.PP
定義在 mm_type\&.h 檔案之第 14 行\&.
.SS "typedef unsigned \fBshort\fP \fBUSHORT\fP"

.PP
定義在 mm_type\&.h 檔案之第 15 行\&.
.SS "typedef unsigned \fBshort\fP \fBint\fP \fBWORD\fP"

.PP
定義在 mm_type\&.h 檔案之第 9 行\&.
.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
