.TH "name_t" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
name_t
.SH SYNOPSIS
.br
.PP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "\fBname_kind_t\fP \fBkind\fP"
.br
.ti -1c
.RI "\fBchar\fP * \fBstring\fP"
.br
.ti -1c
.RI "XID \fBxid\fP"
.br
.ti -1c
.RI "\fBint\fP \fBindex\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 xrandr\&.c 檔案之第 178 行\&.
.SH "資料成員說明文件"
.PP 
.SS "\fBint\fP name_t::index"

.PP
定義在 xrandr\&.c 檔案之第 182 行\&.
.SS "\fBname_kind_t\fP name_t::kind"

.PP
定義在 xrandr\&.c 檔案之第 179 行\&.
.SS "\fBchar\fP* name_t::string"

.PP
定義在 xrandr\&.c 檔案之第 180 行\&.
.SS "XID name_t::xid"

.PP
定義在 xrandr\&.c 檔案之第 181 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
