.TH "rectangle_t" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rectangle_t
.SH SYNOPSIS
.br
.PP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "\fBint\fP \fBx\fP"
.br
.ti -1c
.RI "\fBint\fP \fBy\fP"
.br
.ti -1c
.RI "\fBint\fP \fBwidth\fP"
.br
.ti -1c
.RI "\fBint\fP \fBheight\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 xrandr\&.c 檔案之第 140 行\&.
.SH "資料成員說明文件"
.PP 
.SS "\fBint\fP rectangle_t::height"

.PP
定義在 xrandr\&.c 檔案之第 141 行\&.
.SS "\fBint\fP rectangle_t::width"

.PP
定義在 xrandr\&.c 檔案之第 141 行\&.
.SS "\fBint\fP rectangle_t::x"

.PP
定義在 xrandr\&.c 檔案之第 141 行\&.
.SS "\fBint\fP rectangle_t::y"

.PP
定義在 xrandr\&.c 檔案之第 141 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
