.TH "task_t" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
task_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EncodeEngine\&.h>\fP
.SS "公開屬性"

.in +1c
.ti -1c
.RI "unsigned \fBchar\fP * \fBbmp_buffer\fP"
.br
.ti -1c
.RI "unsigned \fBchar\fP * \fBpBitstream\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBwidth\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBheight\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBpitch\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBh_blocks\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBv_blocks\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBszframebuffer\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBfilelen\fP"
.br
.ti -1c
.RI "bool \fBresolution_chahged\fP"
.br
.ti -1c
.RI "bool \fBfirst\fP"
.br
.in -1c
.SH "詳細描述"
.PP 
定義在 EncodeEngine\&.h 檔案之第 20 行\&.
.SH "資料成員說明文件"
.PP 
.SS "unsigned \fBchar\fP* task_t::bmp_buffer"

.PP
定義在 EncodeEngine\&.h 檔案之第 21 行\&.
.SS "unsigned \fBint\fP task_t::filelen"

.PP
定義在 EncodeEngine\&.h 檔案之第 29 行\&.
.SS "bool task_t::first"

.PP
定義在 EncodeEngine\&.h 檔案之第 31 行\&.
.SS "unsigned \fBint\fP task_t::h_blocks"

.PP
定義在 EncodeEngine\&.h 檔案之第 26 行\&.
.SS "unsigned \fBint\fP task_t::height"

.PP
定義在 EncodeEngine\&.h 檔案之第 24 行\&.
.SS "unsigned \fBchar\fP* task_t::pBitstream"

.PP
定義在 EncodeEngine\&.h 檔案之第 22 行\&.
.SS "unsigned \fBint\fP task_t::pitch"

.PP
定義在 EncodeEngine\&.h 檔案之第 25 行\&.
.SS "bool task_t::resolution_chahged"

.PP
定義在 EncodeEngine\&.h 檔案之第 30 行\&.
.SS "unsigned \fBint\fP task_t::szframebuffer"

.PP
定義在 EncodeEngine\&.h 檔案之第 28 行\&.
.SS "unsigned \fBint\fP task_t::v_blocks"

.PP
定義在 EncodeEngine\&.h 檔案之第 27 行\&.
.SS "unsigned \fBint\fP task_t::width"

.PP
定義在 EncodeEngine\&.h 檔案之第 23 行\&.

.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
