.TH "/home/odin/Desktop/program/usbdisp_linux/libusbdisp/usbdev.h" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/odin/Desktop/program/usbdisp_linux/libusbdisp/usbdev.h
.SH SYNOPSIS
.br
.PP
\fC#include 'ClientUSB\&.h'\fP
.br
\fC#include <libusb\-1\&.0/libusb\&.h>\fP
.br

.SS "複合項目"

.in +1c
.ti -1c
.RI "class \fBusbdev\fP"
.br
.in -1c
.SS "定義"

.in +1c
.ti -1c
.RI "#define \fBVID\fP   0x04FC"
.br
.ti -1c
.RI "#define \fBPID\fP   0x2103"
.br
.ti -1c
.RI "#define \fBINTERFACE\fP   2"
.br
.ti -1c
.RI "#define \fBEPADDR\fP   2"
.br
.in -1c
.SH "定義巨集說明文件"
.PP 
.SS "#define EPADDR   2"

.PP
定義在 usbdev\&.h 檔案之第 50 行\&.
.SS "#define INTERFACE   2"

.PP
定義在 usbdev\&.h 檔案之第 49 行\&.
.SS "#define PID   0x2103"

.PP
定義在 usbdev\&.h 檔案之第 48 行\&.
.SS "#define VID   0x04FC"

.PP
定義在 usbdev\&.h 檔案之第 47 行\&.
.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
