.TH "/home/odin/Desktop/program/usbdisp_linux/libusbdisp/xrandr.h" 3 "2024年11月2日 星期六" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/odin/Desktop/program/usbdisp_linux/libusbdisp/xrandr.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <X11/Xlib\&.h>\fP
.br
\fC#include <X11/Xutil\&.h>\fP
.br
\fC#include <X11/extensions/XShm\&.h>\fP
.br
\fC#include <X11/extensions/Xrandr\&.h>\fP
.br

.SS "複合項目"

.in +1c
.ti -1c
.RI "struct \fBshmimage\fP"
.br
.ti -1c
.RI "class \fBX11_Screen\fP"
.br
.in -1c
.SS "變數"

.in +1c
.ti -1c
.RI "unsigned \fBchar\fP const \fBCursor_image\fP [16 *40]"
.br
.in -1c
.SH "變數說明文件"
.PP 
.SS "unsigned \fBchar\fP const Cursor_image[16 *40]"

.PP
定義在 xrandr\&.h 檔案之第 18 行\&.
.SH "作者"
.PP 
本文件由Doxygen 自 My Project 的原始碼中自動產生\&.
