var searchData=
[
  ['dhtinfotype_852',['DHTinfotype',['../struct_d_h_tinfotype.html',1,'']]],
  ['dqtinfotype_853',['DQTinfotype',['../struct_d_q_tinfotype.html',1,'']]],
  ['drm_5fevdi_5fconnect_854',['drm_evdi_connect',['../structdrm__evdi__connect.html',1,'']]],
  ['drm_5fevdi_5fconnect32_855',['drm_evdi_connect32',['../structdrm__evdi__connect32.html',1,'']]],
  ['drm_5fevdi_5fddcci_5fresponse_856',['drm_evdi_ddcci_response',['../structdrm__evdi__ddcci__response.html',1,'']]],
  ['drm_5fevdi_5fenable_5fcursor_5fevents_857',['drm_evdi_enable_cursor_events',['../structdrm__evdi__enable__cursor__events.html',1,'']]],
  ['drm_5fevdi_5fevent_5fcrtc_5fstate_858',['drm_evdi_event_crtc_state',['../structdrm__evdi__event__crtc__state.html',1,'']]],
  ['drm_5fevdi_5fevent_5fcursor_5fmove_859',['drm_evdi_event_cursor_move',['../structdrm__evdi__event__cursor__move.html',1,'']]],
  ['drm_5fevdi_5fevent_5fcursor_5fset_860',['drm_evdi_event_cursor_set',['../structdrm__evdi__event__cursor__set.html',1,'']]],
  ['drm_5fevdi_5fevent_5fddcci_5fdata_861',['drm_evdi_event_ddcci_data',['../structdrm__evdi__event__ddcci__data.html',1,'']]],
  ['drm_5fevdi_5fevent_5fdpms_862',['drm_evdi_event_dpms',['../structdrm__evdi__event__dpms.html',1,'']]],
  ['drm_5fevdi_5fevent_5fmode_5fchanged_863',['drm_evdi_event_mode_changed',['../structdrm__evdi__event__mode__changed.html',1,'']]],
  ['drm_5fevdi_5fevent_5fupdate_5fready_864',['drm_evdi_event_update_ready',['../structdrm__evdi__event__update__ready.html',1,'']]],
  ['drm_5fevdi_5fgrabpix_865',['drm_evdi_grabpix',['../structdrm__evdi__grabpix.html',1,'']]],
  ['drm_5fevdi_5fgrabpix32_866',['drm_evdi_grabpix32',['../structdrm__evdi__grabpix32.html',1,'']]],
  ['drm_5fevdi_5frequest_5fupdate_867',['drm_evdi_request_update',['../structdrm__evdi__request__update.html',1,'']]]
];
